# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: branch_development

test:
  <<: *default
  database: travis_ci_test

production:
  <<: *default
  database: branch_production
  username: branch
  password: <%= ENV['BRANCH_DATABASE_PASSWORD'] %>
